### ISSUE TITLE
YouTube Links einbinden

### ISSUE THREAD

**Issue by demianh** [rondo-verlag/rondo-app#13]
Im Song Manager haben wir jetzt bei vielen Songs auch einen Youtube Link erfasst. Ich würde den Youtube Link auf der Noten-Seite oben einbinden.

- [ ] Braucht auch ein Update des Song-Manager Exports
- [ ] Benötigt ein neues Icon (=> Lennon fragen)

**Comment by Vento-Nuenenen** [comment]
Siehe PR
