### ISSUE TITLE
Cordova Purchase Plugin ersetzen

### ISSUE THREAD

**Issue by Vento-Nuenenen** [rondo-verlag/rondo-app#50]
In der aktuellen version funktioniert das Package @awesome-cordova-plugins/in-app-purchase-2 nicht mehr

https://github.com/danielsogl/awesome-cordova-plugins/issues/4457

**Comment by demianh** [comment]
Bei mir funktioniert das In-App Purchase Package auch mit Ionic 7. Habe es darum wieder aktiviert

**Comment by demianh** [comment]
@Vento-Nuenenen kannst du mal schauen, ob es bei dir jetzt auch wieder funktioniert? Wenn ja, können wir das Issue schliessen :)
